# SQLite version 3.x
#   gem install sqlite3
development:
  adapter: mysql
  database: lift_development
  host: 127.0.0.1
  username: root
  password: 
  pool: 5
  timeout: 5000
  encoding: utf8

test:
    adapter: mysql
    database: lift_test
    host: 127.0.0.1
    username: root
    password: 
    pool: 5
    timeout: 5000
    encoding: utf8

production:
    adapter: mysql
    database: lift_production
    host: 127.0.0.1
    username: root
    password: 
    pool: 5
    timeout: 5000
    encoding: utf8
